### ISSUE TITLE
make: *** No rule to make target 'out/src/generic/timer_irq.o', needed by 'out/katapult.elf'.  Stop.

### ISSUE THREAD

**Issue by Bones116XIVI** [Arksine/katapult#166]
im going through the steps to flash my EBB36 and i keep getting this message after i enter the make cmd. im in the correct directory. i entered the correct data in the menuconfig, i tried to make clean and re compile and still to no avail. i am not that proficient as far as trouble shooting these issues, is there anyone that could help me out here?

**Comment by pgsengstock** [comment]
Seeing the same thing trying to build for an M8P.  Running origin/master, freshly cloned.  Combing through the recent commits now, but not spotting anything obvious.

**Comment by pgsengstock** [comment]
Narrowed down to commit 3f84643.

**Comment by pgsengstock** [comment]
Not sure, but I think src/stm32/Makefile need lines 42-43 edited as follows:
`timer-src-$(CONFIG_MACH_STM32F0) := stm32/stm32f0_timer.c
timer-src-$(CONFIG_MACH_STM32G0) := stm32/stm32f0_timer.c`

At least, that makes it build properly.  No clue if it breaks anything.

**Comment by KirkSturg** [comment]
I too am having the same issue.  Based on the error it looks likes some kind of file issue or spelling issue.  Anyone have a update for a fix?

**Comment by spamwax** [comment]
Getting the same error (compiling for an EBB42). it seems the organizational change made in that commit has broken the Makefile

**Comment by Arksine** [comment]
Thanks.  This should be fixed in commit a8e44fd3089cf94cb0ace970c4148f6aab078cc0.

**Comment by Arksine** [comment]
Thanks.  The deployer build errors should now be fixed as well.

**Comment by Bones116XIVI** [comment]
still having issues with the makefile  Linking out/deployer.elf
/usr/lib/gcc/arm-none-eabi/8.3.1/../../../arm-none-eabi/bin/ld: out/src/generic/armcm_boot.o: in function `reset_handler_stage_two':
/home/bones/katapult/src/generic/armcm_boot.c:103: undefined reference to `armcm_main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:99: out/deployer.elf] Error 1
this is definitely putting a damper on my printers pushing plastic capabilities lol.

**Comment by Printathan** [comment]
Worked for me just now after updating

**Comment by Bones116XIVI** [comment]
what steps did you take

**Comment by Bones116XIVI** [comment]
im not the most proficient

**Comment by Bones116XIVI** [comment]
sudo apt update and upgrade?

**Comment by Printathan** [comment]
I'm following Esoterical's can bus guide and just started back at "Installing Katapult" and ran `test -e ~/katapult && (cd ~/katapult && git pull) || (cd ~ && git clone https://github.com/Arksine/katapult) ; cd ~
`

**Comment by Bones116XIVI** [comment]
how do i remove the katapult directory i tried sudo rm ~/katapult

**Comment by Bones116XIVI** [comment]
yeah im still getting the same error

**Comment by pgsengstock** [comment]
Worked for me just fine after updating. From inside the cloned repo, just run `git pull` to update.

**Comment by spamwax** [comment]
> yeah im still getting the same error

a clean up should fix it, this will work if `katapult` was originally in your home folder:

```bash
cd ~
rm -rf katapult
git clone https://github.com/Arksine/katapult
cd katapult
make menuconfig # adjust the setting according to your board
make clean
make
```

**Comment by Bones116XIVI** [comment]
thanks man

**Comment by infinitevalence** [comment]
Updated my local repo, and this fixed the issue.  Thanks!
